apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-nestjs-worker
  labels:
    app.kubernetes.io/name: boilerplate-nestjs-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: boilerplate-nestjs-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: boilerplate-nestjs-worker
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: REPLACE_ME_IMAGE
          imagePullPolicy: IfNotPresent
          command: ["/nodejs/bin/node", "dist/worker.js"]
          envFrom:
            - configMapRef:
                name: boilerplate-nestjs-config
            - secretRef:
                name: boilerplate-nestjs-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
